### ISSUE TITLE
Getting error `Undefined variable: s:NoMapPreYankPos`

### ISSUE THREAD

**Issue by farzadmf** [svban/YankAssassin.vim#3]
Hi, I'm getting this error from time to time when yanking:
```
Error detected while processing function <SNR>272_YankAssassin:
line    1:
E121: Undefined variable: s:NoMapPreYankPos
```

Unfortunately, I'm not exactly sure how to reproduce this; sometimes it happens and sometimes it doesn't.

I was wondering if you know what the reason would be. I have A LOT of plugins installed, so it might be because of those, but I thought I might ask you

**Comment by lcrockett** [comment]
Same here. Nvim v0.6.1 @ Ubuntu 20.04 | macOS Big Sur.

**Comment by svban** [comment]
Fixed it

**Comment by DEliasVCruz** [comment]
I'm getting the same error except that it only happens when I try to lazy load the plugin on `TextYankPost` event with packer

```lua
  use { "svban/YankAssassin.vim", event = "TextYankPost" }
```

I get this error when calling the mapping for the first time:

```
Please check your config for correctness
Se ha detectado un error al procesar function <SNR>62_YankAssassin:
línea    1
E121: Undefined variable: s:NoMapPreYankPos
```

On a side note, I had some other problems with lazy loading another plugin with the `TextYankPost` event and it resulted in this  pull request [wbthomason/packer.nvim#636](https://github.com/wbthomason/packer.nvim/pull/636) it might be related
